apiVersion: v1
kind: Secret
metadata:
  name: {{ include "audit-trail.fullname" . }}-secret
  labels:
    {{- include "audit-trail.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.postgresql.enabled }}
  SPRING_DATASOURCE_USERNAME: {{ .Values.postgresql.auth.username | b64enc | quote }}
  {{- if .Values.postgresql.auth.password }}
  SPRING_DATASOURCE_PASSWORD: {{ .Values.postgresql.auth.password | b64enc | quote }}
  {{- end }}
  {{- else }}
  SPRING_DATASOURCE_USERNAME: {{ .Values.externalDatabase.username | b64enc | quote }}
  {{- if .Values.externalDatabase.password }}
  SPRING_DATASOURCE_PASSWORD: {{ .Values.externalDatabase.password | b64enc | quote }}
  {{- end }}
  {{- end }}

  {{- if and (not .Values.redis.enabled) .Values.externalRedis.password }}
  SPRING_DATA_REDIS_PASSWORD: {{ .Values.externalRedis.password | b64enc | quote }}
  {{- end }}
