spring:
  elasticsearch:
    uris: ${SPRING_ELASTICSEARCH_URIS:http://localhost:9200}
    username: ${SPRING_ELASTICSEARCH_USERNAME:}
    password: ${SPRING_ELASTICSEARCH_PASSWORD:}

search:
  index:
    name: ${ELASTICSEARCH_INDEX_NAME:events}
    shards: ${ELASTICSEARCH_INDEX_SHARDS:1}
    replicas: ${ELASTICSEARCH_INDEX_REPLICAS:0}
